import leather_jacket from "@/public/images/products/leather_jacket.webp"
import leather_handbag from "@/public/images/products/leather_handbag.webp"
import leather_boots from "@/public/images/products/leather_boots.webp"
import leather_shoes from "@/public/images/products/leather_shoes.webp"
import leather_backpack from "@/public/images/products/leather_backpack.webp"
import leather_briefcase from "@/public/images/products/leather_briefcase.webp"
import leather_gloves from "@/public/images/products/leather_gloves.webp"
import leather_toolbag from "@/public/images/products/leather_toolbag.webp"
import leather_wallet from "@/public/images/products/leather_wallet.webp"
import leather_belt from "@/public/images/products/leather_belt.webp"
import leather_slippers from "@/public/images/products/leather_slippers.webp"
import leather_clutches from "@/public/images/products/leather_clutches.webp"
import leather_coat from "@/public/images/products/leather_coat.webp"
import leather_vest from "@/public/images/products/leather_vest.webp"
import leather_moccasins from "@/public/images/products/leather_moccasins.webp"
import leather_loafers from "@/public/images/products/leather_loafers.webp"
import leather_cricket_ball from "@/public/images/products/leather_cricket_ball.webp"
import leather_saddle from "@/public/images/products/leather_saddle.webp"
import leather_safety_gloves from "@/public/images/products/leather_safety_gloves.webp"
import leather_car_seat_cover from "@/public/images/products/leather_car_seat_cover.webp"
import leather_car_seat_cover_2 from "@/public/images/products/leather_car_seat_cover_2.webp"
import leather_bag_set from "@/public/images/products/leather_bag_set.webp"
import leather_keychains from "@/public/images/products/leather_keychains.webp"
import leather_table_mats from "@/public/images/products/leather_table_mats.webp"
import leather_office_chair from "@/public/images/products/leather_office_chair.webp"
import leather_slippers_2 from "@/public/images/products/leather_slippers_2.webp"
import leather_belt_2 from "@/public/images/products/leather_belt_2.webp"
import leather_wallet_pouch from "@/public/images/products/leather_wallet_pouch.webp"
import fashion_leather_gloves from "@/public/images/products/fashion-leather-gloves.webp"
import leather_jacket_women from "@/public/images/products/leather_jacket_women.webp"

export const products = [
  {
    id: "leather-jacket",
    name: "Classic Leather Jacket",
    description: "A timeless leather jacket crafted from premium full-grain leather with a comfortable fit and durable construction.",
    price: 29500,
    image: leather_jacket,
    category: "apparel",
    color: "Brown",
    featured: true,
    rating: 4.8,
    reviewCount: 124,
    date: "2023-01-15",
  },
  {
    id: "leather-handbag",
    name: "Elegant Leather Handbag",
    description: "An elegant handbag designed with premium leather and meticulous craftsmanship for everyday use.",
    price: 14500,
    image: leather_handbag,
    category: "accessories",
    color: "Brown",
    featured: true,
    rating: 4.6,
    reviewCount: 98,
    date: "2023-03-10",
  },
  {
    id: "leather-boots",
    name: "Classic Leather Boots",
    description: "Classic leather boots made with genuine leather, featuring durable construction and comfortable fit.",
    price: 18500,
    image: leather_boots,
    category: "footwear",
    color: "Brown",
    featured: true,
    rating: 4.9,
    reviewCount: 75,
    date: "2023-02-05",
  },
  {
    id: "leather-shoes",
    name: "Leather Oxford Shoes",
    description: "Elegant Oxford shoes crafted from premium leather with traditional closed lacing system.",
    price: 15500,
    image: leather_shoes,
    category: "footwear",
    color: "Brown",
    featured: false,
    rating: 4.7,
    reviewCount: 62,
    date: "2023-04-20",
  },
  {
    id: "leather-backpack",
    name: "Leather Backpack",
    description: "A stylish and functional leather backpack perfect for daily use or travel.",
    price: 12500,
    image: leather_backpack,
    category: "accessories",
    color: "Brown",
    featured: true,
    rating: 4.5,
    reviewCount: 110,
    date: "2023-01-25",
  },
  {
    id: "leather-briefcase",
    name: "Professional Leather Briefcase",
    description: "A professional leather briefcase designed for business use with multiple compartments.",
    price: 24500,
    image: leather_briefcase,
    category: "accessories",
    color: "Black",
    featured: false,
    rating: 4.4,
    reviewCount: 48,
    date: "2023-05-15",
  },
  {
    id: "leather-gloves",
    name: "Leather Work Gloves",
    description: "Heavy-duty work gloves made from durable leather, designed for industrial use and protection.",
    price: 3500,
    image: leather_gloves,
    category: "industrial",
    color: "Brown",
    featured: false,
    rating: 4.3,
    reviewCount: 37,
    date: "2023-06-10",
  },
  {
    id: "leather-toolbag",
    name: "Leather Tool Bag",
    description: "A professional-grade leather tool bag with multiple pockets and compartments for all your tools.",
    price: 7500,
    image: leather_toolbag,
    category: "industrial",
    color: "Brown",
    featured: true,
    rating: 4.7,
    reviewCount: 52,
    date: "2023-03-25",
  },
  {
    id: "leather-wallet",
    name: "Classic Leather Wallet",
    description: "A timeless leather wallet with multiple card slots and a bill compartment.",
    price: 2500,
    image: leather_wallet,
    category: "accessories",
    color: "Brown",
    featured: true,
    rating: 4.6,
    reviewCount: 89,
    date: "2023-07-01",
  },
  {
    id: "leather-belt",
    name: "Genuine Leather Belt",
    description: "A classic leather belt crafted from premium leather with a durable buckle.",
    price: 1500,
    image: leather_belt,
    category: "accessories",
    color: "Brown",
    featured: false,
    rating: 4.5,
    reviewCount: 45,
    date: "2023-08-15",
  },
  {
    id: "leather-slippers",
    name: "Comfortable Leather Slippers",
    description: "Soft and comfortable leather slippers perfect for indoor wear.",
    price: 2500,
    image: leather_slippers,
    category: "footwear",
    color: "Brown",
    featured: false,
    rating: 4.4,
    reviewCount: 33,
    date: "2023-09-20",
  },
  {
    id: "leather-clutches",
    name: "Leather Clutch Set",
    description: "A set of elegant leather clutches in different sizes for various occasions.",
    price: 5500,
    image: leather_clutches,
    category: "accessories",
    color: "Brown",
    featured: true,
    rating: 4.7,
    reviewCount: 67,
    date: "2023-10-05",
  },
  {
    id: "leather-coat",
    name: "Premium Leather Coat",
    description: "A luxurious leather coat perfect for cold weather with premium craftsmanship.",
    price: 32500,
    image: leather_coat,
    category: "apparel",
    color: "Black",
    featured: true,
    rating: 4.8,
    reviewCount: 92,
    date: "2023-11-01",
  },
  {
    id: "leather-vest",
    name: "Leather Vest",
    description: "A stylish leather vest that adds a touch of sophistication to any outfit.",
    price: 22500,
    image: leather_vest,
    category: "apparel",
    color: "Brown",
    featured: false,
    rating: 4.5,
    reviewCount: 58,
    date: "2023-12-10",
  },
  {
    id: "leather-moccasins",
    name: "Classic Leather Moccasins",
    description: "Comfortable leather moccasins with traditional design and soft sole.",
    price: 4500,
    image: leather_moccasins,
    category: "footwear",
    color: "Brown",
    featured: false,
    rating: 4.6,
    reviewCount: 42,
    date: "2024-01-15",
  },
  {
    id: "leather-loafers",
    name: "Leather Loafers",
    description: "Elegant leather loafers perfect for both casual and formal occasions.",
    price: 5500,
    image: leather_loafers,
    category: "footwear",
    color: "Brown",
    featured: true,
    rating: 4.7,
    reviewCount: 78,
    date: "2024-02-01",
  },
  {
    id: "leather-cricket-ball",
    name: "Premium Leather Cricket Ball",
    description: "Professional-grade leather cricket ball with perfect weight and balance.",
    price: 2500,
    image: leather_cricket_ball,
    category: "sports",
    color: "Red",
    featured: false,
    rating: 4.6,
    reviewCount: 45,
    date: "2024-02-15",
  },
  {
    id: "leather-saddle",
    name: "Equestrian Leather Saddle",
    description: "High-quality leather saddle designed for comfort and durability.",
    price: 28500,
    image: leather_saddle,
    category: "equestrian",
    color: "Brown",
    featured: true,
    rating: 4.8,
    reviewCount: 32,
    date: "2024-02-20",
  },
  {
    id: "leather-safety-gloves",
    name: "Safety Leather Gloves",
    description: "Industrial safety gloves with reinforced leather protection.",
    price: 4500,
    image: leather_safety_gloves,
    category: "industrial",
    color: "Brown",
    featured: false,
    rating: 4.4,
    reviewCount: 28,
    date: "2024-02-25",
  },
  {
    id: "leather-car-seat-cover",
    name: "Luxury Car Seat Covers",
    description: "Premium leather car seat covers for ultimate comfort and style.",
    price: 12500,
    image: leather_car_seat_cover,
    category: "automotive",
    color: "Black",
    featured: true,
    rating: 4.7,
    reviewCount: 85,
    date: "2024-03-01",
  },
  {
    id: "leather-bag-set",
    name: "Leather Bag Collection",
    description: "Complete set of leather bags for various occasions.",
    price: 18500,
    image: leather_bag_set,
    category: "accessories",
    color: "Brown",
    featured: true,
    rating: 4.6,
    reviewCount: 62,
    date: "2024-03-05",
  },
  {
    id: "leather-keychains",
    name: "Leather Keychain Set",
    description: "Stylish leather keychains with unique designs.",
    price: 1500,
    image: leather_keychains,
    category: "accessories",
    color: "Brown",
    featured: false,
    rating: 4.5,
    reviewCount: 38,
    date: "2024-03-10",
  },
  {
    id: "leather-table-mats",
    name: "Leather Table Mats",
    description: "Elegant leather table mats for dining and decoration.",
    price: 3500,
    image: leather_table_mats,
    category: "home",
    color: "Brown",
    featured: false,
    rating: 4.4,
    reviewCount: 42,
    date: "2024-03-15",
  },
  {
    id: "leather-office-chair",
    name: "Leather Office Chair",
    description: "Ergonomic leather office chair for maximum comfort.",
    price: 22500,
    image: leather_office_chair,
    category: "furniture",
    color: "Black",
    featured: true,
    rating: 4.7,
    reviewCount: 75,
    date: "2024-03-20",
  },
  {
    id: "leather-slippers-2",
    name: "Premium Leather Slippers",
    description: "Luxurious leather slippers with soft lining.",
    price: 3500,
    image: leather_slippers_2,
    category: "footwear",
    color: "Brown",
    featured: false,
    rating: 4.5,
    reviewCount: 48,
    date: "2024-03-25",
  },
  {
    id: "leather-belt-2",
    name: "Designer Leather Belt",
    description: "Fashionable leather belt with unique buckle design.",
    price: 2500,
    image: leather_belt_2,
    category: "accessories",
    color: "Brown",
    featured: false,
    rating: 4.4,
    reviewCount: 35,
    date: "2024-03-30",
  },
  {
    id: "leather-wallet-pouch",
    name: "Leather Wallet Pouch",
    description: "Compact leather wallet pouch for essentials.",
    price: 2000,
    image: leather_wallet_pouch,
    category: "accessories",
    color: "Brown",
    featured: false,
    rating: 4.3,
    reviewCount: 28,
    date: "2024-04-01",
  },
  {
    id: "fashion-leather-gloves",
    name: "Fashion Leather Gloves",
    description: "Stylish leather gloves for fashion and warmth.",
    price: 4500,
    image: fashion_leather_gloves,
    category: "apparel",
    color: "Brown",
    featured: true,
    rating: 4.6,
    reviewCount: 52,
    date: "2024-04-05",
  },
  {
    id: "leather-jacket-women",
    name: "Women's Leather Jacket",
    description: "Elegant leather jacket designed specifically for women.",
    price: 27500,
    image: leather_jacket_women,
    category: "apparel",
    color: "Black",
    featured: true,
    rating: 4.8,
    reviewCount: 95,
    date: "2024-04-10",
  },
  {
    id: "leather-car-seat-cover-2",
    name: "Leather Car Seat Cover", 
    description: "Elegant leather jacket designed specifically for women.",
    price: 15270,
    image: leather_car_seat_cover_2,
    category: "apparel",
    color: "Black",
    featured: true,
    rating: 4.8,
    reviewCount: 95,
    date: "2024-04-10",
  }
]

